version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: urbango_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: urbango
      MYSQL_USER: urbango
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
